# The directory where models and summaries will be saved (Inside the run_dir parent directory).. It is created if it does not exist.
model_dir: /mnt/work/onmt-tf/mdt/to_en/model_pten

###############################################################################################

data:
  # (required for train_and_eval and train run types).
  train_features_file: train.pt.tok
  train_labels_file: train.en.tok

  # (required for train_end_eval and eval run types).
  eval_features_file: valid.pt.tok
  eval_labels_file: valid.en.tok

  # (optional) Models may require additional resource files (e.g. vocabularies).
  # Use the same BPE as we had for the base models
  source_words_vocabulary: /mnt/work/onmt-tf/mdt/to_en/model_pten/assets/shared.bpe
  target_words_vocabulary: /mnt/work/onmt-tf/mdt/to_en/model_pten/assets/shared.bpe

###############################################################################################

train:
  save_checkpoints_steps: 10000
  keep_checkpoint_max: 5000
  save_summary_steps: 10000
  train_steps: 28000000  # less than ckpt_start + product of two above = 1.54m + 4K*200

eval:
  eval_delay: 70 #drop vs GP in same ratio as Data itself (90m to 8m)
  external_evaluators: BLEU
  exporters: last
